In [1]:
!pip install duckdb

Defaulting to user installation because normal site-packages is not writeable
Collecting duckdb
  Downloading duckdb-1.5.3-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Downloading duckdb-1.5.3-cp313-cp313-win_amd64.whl (13.1 MB)
   ---------------------------------------- 0.0/13.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/13.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/13.1 MB ? eta -:--:--
    --------------------------------------- 0.3/13.1 MB ? eta -:--:--
    --------------------------------------- 0.3/13.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/13.1 MB 1.0 MB/s eta 0:00:13
   -- ------------------------------------- 0.8/13.1 MB 929.5 kB/s eta 0:00:14
   -- ------------------------------------- 0.8/13.1 MB 929.5 kB/s eta 0:00:14
   --- ------------------------------------ 1.0/13.1 MB 850.8 kB/s eta 0:00:15
   --- ------------------------------------ 1.0/13.1 MB 850.8 kB/s eta 0:00:15
   --- ------------------------------------ 1.3/13.1 MB 762.7 kB/s eta 0:00:16
   ---- ----------------------------------- 1.6/13.1 MB 755.1 kB/s eta 0:00:16
   ---- ----------------------------------- 1.6/13.1 MB 755.1 kB/s eta 0:00:16
   ----- ---------------------------------- 1.8/13.1 MB 776.8 kB/s eta 0:00:15
   ------- -------------------------------- 2.4/13.1 MB 901.4 kB/s eta 0:00:12
   -------- ------------------------------- 2.9/13.1 MB 1.0 MB/s eta 0:00:10
   ---------- ----------------------------- 3.4/13.1 MB 1.1 MB/s eta 0:00:09
   ----------- ---------------------------- 3.7/13.1 MB 1.2 MB/s eta 0:00:09
   ----------- ---------------------------- 3.7/13.1 MB 1.2 MB/s eta 0:00:09
   ----------- ---------------------------- 3.9/13.1 MB 1.1 MB/s eta 0:00:09
   ------------- -------------------------- 4.5/13.1 MB 1.2 MB/s eta 0:00:08
   -------------- ------------------------- 4.7/13.1 MB 1.2 MB/s eta 0:00:08
   --------------- ------------------------ 5.0/13.1 MB 1.2 MB/s eta 0:00:07
   ----------------- ---------------------- 5.8/13.1 MB 1.3 MB/s eta 0:00:06
   ------------------- -------------------- 6.6/13.1 MB 1.4 MB/s eta 0:00:05
   ----------------------- ---------------- 7.6/13.1 MB 1.6 MB/s eta 0:00:04
   ------------------------- -------------- 8.4/13.1 MB 1.7 MB/s eta 0:00:03
   --------------------------- ------------ 9.2/13.1 MB 1.8 MB/s eta 0:00:03
   ------------------------------ --------- 10.0/13.1 MB 1.8 MB/s eta 0:00:02
   ------------------------------- -------- 10.5/13.1 MB 1.9 MB/s eta 0:00:02
   -------------------------------- ------- 10.7/13.1 MB 1.9 MB/s eta 0:00:02
   ---------------------------------- ----- 11.3/13.1 MB 1.9 MB/s eta 0:00:01
   ----------------------------------- ---- 11.5/13.1 MB 1.9 MB/s eta 0:00:01
   ------------------------------------ --- 12.1/13.1 MB 1.9 MB/s eta 0:00:01
   -------------------------------------- - 12.6/13.1 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  13.1/13.1 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 13.1/13.1 MB 1.9 MB/s  0:00:07
Installing collected packages: duckdb
Successfully installed duckdb-1.5.3

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: C:\Users\tshiv\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import duckdb

# 1. Create a standard Pandas DataFrame
df_sales = pd.DataFrame({
    'Team': ['Data_Engineering', 'Data_Engineering', 'AI_Research', 'AI_Research'],
    'Project': ['Pipeline A', 'Database B', 'Model X', 'Vision Y'],
    'Score': [85, 95, 88, 92]
})

print("--- Original Pandas Data ---")
display(df_sales)

--- Original Pandas Data ---

               Team     Project  Score
0  Data_Engineering  Pipeline A     85
1  Data_Engineering  Database B     95
2       AI_Research     Model X     88
3       AI_Research    Vision Y     92

In [3]:
# 2. Write your SQL Query as a text string
# Notice how we just select FROM 'df_sales' (the Python variable name!)

my_query = """
SELECT
    Team,
    AVG(Score) AS Average_Score
FROM df_sales
GROUP BY TEAM;
"""

# 3. Run the SQL query using DuckDB and output the result as a new Pandas table (.df)
sql_result = duckdb.query(my_query).df()

print("--- DuckDB SQL Result ---")
display(sql_result)

--- DuckDB SQL Result ---

               Team  Average_Score
0       AI_Research           90.0
1  Data_Engineering           90.0

In [15]:
# Write a SQL query to find the total revenue and total quantity sold for each product in the 'Electronics' category, 
# but only include products where the total revenue generated is greater than $500.
import pandas as pd
import duckdb

df_products = pd.DataFrame({
    'OrderID': [101, 102, 103, 104, 105, 106],
    'Category': ['Electronics', 'Electronics', 'Clothing', 'Electronics', 'Clothing', 'Electronics'],
    'Product': ['Laptop', 'Mouse', 'T-Shirt', 'Laptop', 'Jeans', 'Mouse'],
    'Quantity': [1, 5, 2, 2, 1, 10],
    'Price': [1200.00, 50.00, 25.00, 1200.00, 40.00, 50.00]
})


df_products

   OrderID     Category  Product  Quantity   Price
0      101  Electronics   Laptop         1  1200.0
1      102  Electronics    Mouse         5    50.0
2      103     Clothing  T-Shirt         2    25.0
3      104  Electronics   Laptop         2  1200.0
4      105     Clothing    Jeans         1    40.0
5      106  Electronics    Mouse        10    50.0

In [16]:
query_1 = """
SELECT 
    Product,
    SUM(Quantity) AS Total_Quantity,
    SUM(Quantity * price) As Total_Revenue
FROM df_products
WHERE Category = 'Electronics'
GROUP BY Product
Having SUM(Quantity * price) > 500;
"""

duckdb.query(query_1).df()

  Product  Total_Quantity  Total_Revenue
0  Laptop             3.0         3600.0
1   Mouse            15.0          750.0

In [17]:
import pandas as pd
import duckdb

df_hr = pd.DataFrame({
    'EmpName': ['Amit', 'Priya', 'Suresh', 'Rahul', 'Deepa', 'Ananya'],
    'Department': ['IT', 'IT', 'HR', 'Marketing', 'Marketing', 'IT'],
    'JobTitle': ['Engineer', 'Manager', 'Recruiter', 'Analyst', 'Manager', 'Engineer'],
    'Salary': [80000, 120000, 60000, 75000, 110000, 85000]
})

df_hr

  EmpName Department   JobTitle  Salary
0    Amit         IT   Engineer   80000
1   Priya         IT    Manager  120000
2  Suresh         HR  Recruiter   60000
3   Rahul  Marketing    Analyst   75000
4   Deepa  Marketing    Manager  110000
5  Ananya         IT   Engineer   85000

In [20]:
# Your Task: Write a query that groups the employees by Department. For each department, 
# calculate:
# The Total Budget (the sum of all salaries).
# The Employee Count (how many people work there). Hint: Use COUNT(EmpName).
# The Filter: Only show departments where the Total Budget is greater than $150,000.
query_2 = """
SELECT
    Department,
    SUM(Salary) AS Total_Budget,
    COUNT(EmpName) AS Employee_Count
FROM df_hr
GROUP BY Department
Having SUM(Salary) > 150000;
"""
duckdb.query(query_2).df()

  Department  Total_Budget  Employee_Count
0         IT      285000.0               3
1  Marketing      185000.0               2

In [ ]:
import pandas as pd
df_logistics = pd.DataFrame({
    'ShipmentID': [1, 2, 3, 4, 5, 6, 7],
    'Warehouse': ['Mumbai', 'Delhi', 'Mumbai', 'Delhi', 'Chennai', 'Mumbai', 'Chennai'],
    'TransportMode': ['Air', 'Road', 'Air', 'Air', 'Air', 'Road', 'Air'],
    'Weight_kg': [300, 800, 250, 600, 150, 400, 100]
})

df_logistics

   ShipmentID Warehouse TransportMode  Weight_kg
0           1    Mumbai           Air        300
1           2     Delhi          Road        800
2           3    Mumbai           Air        250
3           4     Delhi           Air        600
4           5   Chennai           Air        150
5           6    Mumbai          Road        400
6           7   Chennai           Air        100

In [5]:
# Your Task: Write a query to find the Average Weight and Total Weight of packages sent from each Warehouse.
# The Rules:
# First, only look at packages where TransportMode is exactly 'Air'.
# Group the data by Warehouse.
# Finally, only show the warehouses where their Total Weight of Air packages is greater than 500 kg.

import duckdb
query_3 = """
SELECT
    Warehouse,
    SUM(Weight_kg) AS Total_weight,
    AVG(Weight_kg) AS Average_weight
FROM df_logistics
WHERE TransportMode = 'Air'
GROUP BY Warehouse
Having SUM(Weight_kg) > 500
"""

duckdb.query(query_3).df()

  Warehouse  Total_weight  Average_weight
0    Mumbai         550.0           275.0
1     Delhi         600.0           600.0